// <auto-generated />
using System;
using API.Alimed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Alimed.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205104925_TestWithZalecenia1")]
    partial class TestWithZalecenia1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Alimed.Entities.Lekarz", b =>
                {
                    b.Property<int>("LekarzId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LekarzId"));

                    b.Property<string>("Imie")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("longtext");

                    b.Property<int?>("PlacowkaId")
                        .HasColumnType("int");

                    b.Property<string>("Specjalizacja")
                        .HasColumnType("longtext");

                    b.HasKey("LekarzId");

                    b.HasIndex("PlacowkaId");

                    b.ToTable("Lekarze");
                });

            modelBuilder.Entity("API.Alimed.Entities.Pacjent", b =>
                {
                    b.Property<int>("PacjentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PacjentId"));

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Imie")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("longtext");

                    b.Property<string>("Pesel")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("char(36)");

                    b.HasKey("PacjentId");

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId1")
                        .IsUnique();

                    b.ToTable("Pacjenci");
                });

            modelBuilder.Entity("API.Alimed.Entities.Placowka", b =>
                {
                    b.Property<int>("PlacowkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlacowkaId"));

                    b.Property<string>("Nazwa")
                        .HasColumnType("longtext");

                    b.Property<string>("NumerKonta")
                        .HasColumnType("longtext");

                    b.HasKey("PlacowkaId");

                    b.ToTable("Placowki");
                });

            modelBuilder.Entity("API.Alimed.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("API.Alimed.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("GithubId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GithubName")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("GithubId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Alimed.Entities.Wizyta", b =>
                {
                    b.Property<int>("WizytaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WizytaId"));

                    b.Property<bool>("CzyOdbyta")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataWizyty")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Diagnoza")
                        .HasColumnType("longtext");

                    b.Property<int?>("LekarzId")
                        .HasColumnType("int");

                    b.Property<int?>("PacjentId")
                        .HasColumnType("int");

                    b.Property<int?>("PlacowkaId")
                        .HasColumnType("int");

                    b.HasKey("WizytaId");

                    b.HasIndex("LekarzId");

                    b.HasIndex("PacjentId");

                    b.HasIndex("PlacowkaId");

                    b.ToTable("Wizyty");
                });

            modelBuilder.Entity("API.Alimed.Entities.ZaleceniaDokument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NazwaPliku")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PacjentId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ZawartoscPliku")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("PacjentId");

                    b.ToTable("ZaleceniaDokument");
                });

            modelBuilder.Entity("API.Alimed.Entities.Lekarz", b =>
                {
                    b.HasOne("API.Alimed.Entities.Placowka", "Placowka")
                        .WithMany("Lekarze")
                        .HasForeignKey("PlacowkaId");

                    b.Navigation("Placowka");
                });

            modelBuilder.Entity("API.Alimed.Entities.Pacjent", b =>
                {
                    b.HasOne("API.Alimed.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("API.Alimed.Entities.Pacjent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Alimed.Entities.User", null)
                        .WithOne("Pacjent")
                        .HasForeignKey("API.Alimed.Entities.Pacjent", "UserId1");

                    b.OwnsOne("API.Alimed.Entities.Adres", "AdresZamieszkania", b1 =>
                        {
                            b1.Property<int>("PacjentId")
                                .HasColumnType("int");

                            b1.Property<string>("KodPocztowy")
                                .HasColumnType("longtext");

                            b1.Property<string>("Kraj")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Miasto")
                                .HasColumnType("longtext");

                            b1.Property<string>("NumerDomu")
                                .HasColumnType("longtext");

                            b1.Property<string>("Ulica")
                                .HasColumnType("longtext");

                            b1.HasKey("PacjentId");

                            b1.ToTable("Pacjenci");

                            b1.WithOwner()
                                .HasForeignKey("PacjentId");
                        });

                    b.Navigation("AdresZamieszkania");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Alimed.Entities.Placowka", b =>
                {
                    b.OwnsOne("API.Alimed.Entities.Adres", "AdresPlacowki", b1 =>
                        {
                            b1.Property<int>("PlacowkaId")
                                .HasColumnType("int");

                            b1.Property<string>("KodPocztowy")
                                .HasColumnType("longtext");

                            b1.Property<string>("Kraj")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Miasto")
                                .HasColumnType("longtext");

                            b1.Property<string>("NumerDomu")
                                .HasColumnType("longtext");

                            b1.Property<string>("Ulica")
                                .HasColumnType("longtext");

                            b1.HasKey("PlacowkaId");

                            b1.ToTable("Placowki");

                            b1.WithOwner()
                                .HasForeignKey("PlacowkaId");
                        });

                    b.Navigation("AdresPlacowki");
                });

            modelBuilder.Entity("API.Alimed.Entities.RefreshToken", b =>
                {
                    b.HasOne("API.Alimed.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Alimed.Entities.Wizyta", b =>
                {
                    b.HasOne("API.Alimed.Entities.Lekarz", "Lekarz")
                        .WithMany("Wizyty")
                        .HasForeignKey("LekarzId");

                    b.HasOne("API.Alimed.Entities.Pacjent", "Pacjent")
                        .WithMany("Wizyty")
                        .HasForeignKey("PacjentId");

                    b.HasOne("API.Alimed.Entities.Placowka", "Placowka")
                        .WithMany("Wizyty")
                        .HasForeignKey("PlacowkaId");

                    b.Navigation("Lekarz");

                    b.Navigation("Pacjent");

                    b.Navigation("Placowka");
                });

            modelBuilder.Entity("API.Alimed.Entities.ZaleceniaDokument", b =>
                {
                    b.HasOne("API.Alimed.Entities.Pacjent", null)
                        .WithMany("ZaleceniaDokumenty")
                        .HasForeignKey("PacjentId");
                });

            modelBuilder.Entity("API.Alimed.Entities.Lekarz", b =>
                {
                    b.Navigation("Wizyty");
                });

            modelBuilder.Entity("API.Alimed.Entities.Pacjent", b =>
                {
                    b.Navigation("Wizyty");

                    b.Navigation("ZaleceniaDokumenty");
                });

            modelBuilder.Entity("API.Alimed.Entities.Placowka", b =>
                {
                    b.Navigation("Lekarze");

                    b.Navigation("Wizyty");
                });

            modelBuilder.Entity("API.Alimed.Entities.User", b =>
                {
                    b.Navigation("Pacjent");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
