// <auto-generated />
using System;
using API.Alimed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Alimed.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116112143_AddGodzinyPracyLekarza")]
    partial class AddGodzinyPracyLekarza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Alimed.Entities.GodzinyPracyLekarza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CzasWizytyMinuty")
                        .HasColumnType("int");

                    b.Property<int>("DzienTygodnia")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("GodzinaDo")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("GodzinaOd")
                        .HasColumnType("time(6)");

                    b.Property<int>("LekarzId")
                        .HasColumnType("int");

                    b.Property<int>("PlacowkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LekarzId");

                    b.HasIndex("PlacowkaId");

                    b.ToTable("GodzinyPracyLekarzy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CzasWizytyMinuty = 30,
                            DzienTygodnia = 1,
                            GodzinaDo = new TimeSpan(0, 16, 0, 0, 0),
                            GodzinaOd = new TimeSpan(0, 8, 0, 0, 0),
                            LekarzId = 1,
                            PlacowkaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CzasWizytyMinuty = 30,
                            DzienTygodnia = 2,
                            GodzinaDo = new TimeSpan(0, 16, 0, 0, 0),
                            GodzinaOd = new TimeSpan(0, 8, 0, 0, 0),
                            LekarzId = 1,
                            PlacowkaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CzasWizytyMinuty = 30,
                            DzienTygodnia = 3,
                            GodzinaDo = new TimeSpan(0, 16, 0, 0, 0),
                            GodzinaOd = new TimeSpan(0, 8, 0, 0, 0),
                            LekarzId = 1,
                            PlacowkaId = 1
                        },
                        new
                        {
                            Id = 4,
                            CzasWizytyMinuty = 30,
                            DzienTygodnia = 4,
                            GodzinaDo = new TimeSpan(0, 16, 0, 0, 0),
                            GodzinaOd = new TimeSpan(0, 8, 0, 0, 0),
                            LekarzId = 1,
                            PlacowkaId = 1
                        },
                        new
                        {
                            Id = 5,
                            CzasWizytyMinuty = 30,
                            DzienTygodnia = 5,
                            GodzinaDo = new TimeSpan(0, 16, 0, 0, 0),
                            GodzinaOd = new TimeSpan(0, 8, 0, 0, 0),
                            LekarzId = 1,
                            PlacowkaId = 1
                        });
                });

            modelBuilder.Entity("API.Alimed.Entities.Lekarz", b =>
                {
                    b.Property<int>("LekarzId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LekarzId"));

                    b.Property<string>("Imie")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("longtext");

                    b.Property<int?>("PlacowkaId")
                        .HasColumnType("int");

                    b.Property<string>("Specjalizacja")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LekarzId");

                    b.HasIndex("PlacowkaId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Lekarze");

                    b.HasData(
                        new
                        {
                            LekarzId = 1,
                            Imie = "Jan",
                            Nazwisko = "Kowalski",
                            PlacowkaId = 1,
                            Specjalizacja = "Internista"
                        },
                        new
                        {
                            LekarzId = 2,
                            Imie = "Anna",
                            Nazwisko = "Nowak",
                            PlacowkaId = 1,
                            Specjalizacja = "Pediatra"
                        },
                        new
                        {
                            LekarzId = 3,
                            Imie = "Piotr",
                            Nazwisko = "Zieliński",
                            PlacowkaId = 1,
                            Specjalizacja = "Kardiolog"
                        },
                        new
                        {
                            LekarzId = 4,
                            Imie = "Marta",
                            Nazwisko = "Wójcik",
                            PlacowkaId = 2,
                            Specjalizacja = "Dermatolog"
                        },
                        new
                        {
                            LekarzId = 5,
                            Imie = "Krzysztof",
                            Nazwisko = "Kowalczyk",
                            PlacowkaId = 2,
                            Specjalizacja = "Ortopeda"
                        },
                        new
                        {
                            LekarzId = 6,
                            Imie = "Ewa",
                            Nazwisko = "Lewandowska",
                            PlacowkaId = 2,
                            Specjalizacja = "Ginekolog"
                        },
                        new
                        {
                            LekarzId = 7,
                            Imie = "Tomasz",
                            Nazwisko = "Kaczmarek",
                            PlacowkaId = 3,
                            Specjalizacja = "Neurolog"
                        },
                        new
                        {
                            LekarzId = 8,
                            Imie = "Magdalena",
                            Nazwisko = "Mazur",
                            PlacowkaId = 3,
                            Specjalizacja = "Endokrynolog"
                        },
                        new
                        {
                            LekarzId = 9,
                            Imie = "Robert",
                            Nazwisko = "Więckowski",
                            PlacowkaId = 3,
                            Specjalizacja = "Urolog"
                        },
                        new
                        {
                            LekarzId = 10,
                            Imie = "Joanna",
                            Nazwisko = "Borkowska",
                            PlacowkaId = 3,
                            Specjalizacja = "Okulista"
                        },
                        new
                        {
                            LekarzId = 11,
                            Imie = "Adam",
                            Nazwisko = "Gajewski",
                            PlacowkaId = 3,
                            Specjalizacja = "Pulmonolog"
                        },
                        new
                        {
                            LekarzId = 12,
                            Imie = "Natalia",
                            Nazwisko = "Wróbel",
                            PlacowkaId = 3,
                            Specjalizacja = "Reumatolog"
                        },
                        new
                        {
                            LekarzId = 13,
                            Imie = "Michał",
                            Nazwisko = "Jankowski",
                            PlacowkaId = 3,
                            Specjalizacja = "Hematolog"
                        },
                        new
                        {
                            LekarzId = 14,
                            Imie = "Monika",
                            Nazwisko = "Zając",
                            PlacowkaId = 3,
                            Specjalizacja = "Psychiatra"
                        },
                        new
                        {
                            LekarzId = 15,
                            Imie = "Andrzej",
                            Nazwisko = "Pietrzak",
                            PlacowkaId = 4,
                            Specjalizacja = "Internista"
                        },
                        new
                        {
                            LekarzId = 16,
                            Imie = "Barbara",
                            Nazwisko = "Sikora",
                            PlacowkaId = 4,
                            Specjalizacja = "Pediatra"
                        },
                        new
                        {
                            LekarzId = 17,
                            Imie = "Cezary",
                            Nazwisko = "Kruk",
                            PlacowkaId = 4,
                            Specjalizacja = "Chirurg"
                        },
                        new
                        {
                            LekarzId = 18,
                            Imie = "Daria",
                            Nazwisko = "Lis",
                            PlacowkaId = 4,
                            Specjalizacja = "Anestezjolog"
                        },
                        new
                        {
                            LekarzId = 19,
                            Imie = "Filip",
                            Nazwisko = "Wysocki",
                            PlacowkaId = 4,
                            Specjalizacja = "Kardiolog"
                        },
                        new
                        {
                            LekarzId = 20,
                            Imie = "Gabriela",
                            Nazwisko = "Mazurek",
                            PlacowkaId = 4,
                            Specjalizacja = "Dermatolog"
                        },
                        new
                        {
                            LekarzId = 21,
                            Imie = "Hubert",
                            Nazwisko = "Kołodziej",
                            PlacowkaId = 4,
                            Specjalizacja = "Ortopeda"
                        },
                        new
                        {
                            LekarzId = 22,
                            Imie = "Irena",
                            Nazwisko = "Bąk",
                            PlacowkaId = 4,
                            Specjalizacja = "Ginekolog"
                        },
                        new
                        {
                            LekarzId = 23,
                            Imie = "Jerzy",
                            Nazwisko = "Kalinowski",
                            PlacowkaId = 4,
                            Specjalizacja = "Neurolog"
                        },
                        new
                        {
                            LekarzId = 24,
                            Imie = "Kinga",
                            Nazwisko = "Kwiatkowska",
                            PlacowkaId = 4,
                            Specjalizacja = "Endokrynolog"
                        },
                        new
                        {
                            LekarzId = 25,
                            Imie = "Lech",
                            Nazwisko = "Wiśniewski",
                            PlacowkaId = 4,
                            Specjalizacja = "Urolog"
                        },
                        new
                        {
                            LekarzId = 26,
                            Imie = "Mariola",
                            Nazwisko = "Jasińska",
                            PlacowkaId = 4,
                            Specjalizacja = "Okulista"
                        },
                        new
                        {
                            LekarzId = 27,
                            Imie = "Norbert",
                            Nazwisko = "Olszewski",
                            PlacowkaId = 4,
                            Specjalizacja = "Pulmonolog"
                        },
                        new
                        {
                            LekarzId = 28,
                            Imie = "Olimpia",
                            Nazwisko = "Pająk",
                            PlacowkaId = 4,
                            Specjalizacja = "Reumatolog"
                        },
                        new
                        {
                            LekarzId = 29,
                            Imie = "Paweł",
                            Nazwisko = "Czarnecki",
                            PlacowkaId = 4,
                            Specjalizacja = "Hematolog"
                        },
                        new
                        {
                            LekarzId = 30,
                            Imie = "Renata",
                            Nazwisko = "Górska",
                            PlacowkaId = 4,
                            Specjalizacja = "Psychiatra"
                        },
                        new
                        {
                            LekarzId = 31,
                            Imie = "Sebastian",
                            Nazwisko = "Wróblewski",
                            PlacowkaId = 4,
                            Specjalizacja = "Geriatra"
                        },
                        new
                        {
                            LekarzId = 32,
                            Imie = "Teresa",
                            Nazwisko = "Maciejewska",
                            PlacowkaId = 4,
                            Specjalizacja = "Onkolog"
                        },
                        new
                        {
                            LekarzId = 33,
                            Imie = "Urszula",
                            Nazwisko = "Sobczak",
                            PlacowkaId = 5,
                            Specjalizacja = "Internista"
                        },
                        new
                        {
                            LekarzId = 34,
                            Imie = "Wiktor",
                            Nazwisko = "Michalski",
                            PlacowkaId = 5,
                            Specjalizacja = "Pediatra"
                        },
                        new
                        {
                            LekarzId = 35,
                            Imie = "Zuzanna",
                            Nazwisko = "Adamczyk",
                            PlacowkaId = 5,
                            Specjalizacja = "Chirurg"
                        },
                        new
                        {
                            LekarzId = 36,
                            Imie = "Bartosz",
                            Nazwisko = "Szewczyk",
                            PlacowkaId = 5,
                            Specjalizacja = "Anestezjolog"
                        },
                        new
                        {
                            LekarzId = 37,
                            Imie = "Dagmara",
                            Nazwisko = "Walczak",
                            PlacowkaId = 5,
                            Specjalizacja = "Kardiolog"
                        },
                        new
                        {
                            LekarzId = 38,
                            Imie = "Fryderyk",
                            Nazwisko = "Zieliński",
                            PlacowkaId = 5,
                            Specjalizacja = "Dermatolog"
                        },
                        new
                        {
                            LekarzId = 39,
                            Imie = "Grażyna",
                            Nazwisko = "Baranowska",
                            PlacowkaId = 5,
                            Specjalizacja = "Ortopeda"
                        },
                        new
                        {
                            LekarzId = 40,
                            Imie = "Igor",
                            Nazwisko = "Szymański",
                            PlacowkaId = 5,
                            Specjalizacja = "Ginekolog"
                        },
                        new
                        {
                            LekarzId = 41,
                            Imie = "Jolanta",
                            Nazwisko = "Wojciechowska",
                            PlacowkaId = 5,
                            Specjalizacja = "Neurolog"
                        },
                        new
                        {
                            LekarzId = 42,
                            Imie = "Kamil",
                            Nazwisko = "Krupa",
                            PlacowkaId = 5,
                            Specjalizacja = "Endokrynolog"
                        },
                        new
                        {
                            LekarzId = 43,
                            Imie = "Lidia",
                            Nazwisko = "Piotrowska",
                            PlacowkaId = 5,
                            Specjalizacja = "Urolog"
                        },
                        new
                        {
                            LekarzId = 44,
                            Imie = "Marek",
                            Nazwisko = "Grabowski",
                            PlacowkaId = 5,
                            Specjalizacja = "Okulista"
                        },
                        new
                        {
                            LekarzId = 45,
                            Imie = "Nina",
                            Nazwisko = "Rutkowska",
                            PlacowkaId = 5,
                            Specjalizacja = "Pulmonolog"
                        },
                        new
                        {
                            LekarzId = 46,
                            Imie = "Oskar",
                            Nazwisko = "Kowalski",
                            PlacowkaId = 5,
                            Specjalizacja = "Reumatolog"
                        },
                        new
                        {
                            LekarzId = 47,
                            Imie = "Patrycja",
                            Nazwisko = "Zaręba",
                            PlacowkaId = 5,
                            Specjalizacja = "Hematolog"
                        },
                        new
                        {
                            LekarzId = 48,
                            Imie = "Rafał",
                            Nazwisko = "Barański",
                            PlacowkaId = 5,
                            Specjalizacja = "Psychiatra"
                        },
                        new
                        {
                            LekarzId = 49,
                            Imie = "Sandra",
                            Nazwisko = "Konieczna",
                            PlacowkaId = 5,
                            Specjalizacja = "Geriatra"
                        },
                        new
                        {
                            LekarzId = 50,
                            Imie = "Wiktor",
                            Nazwisko = "Krawczyk",
                            PlacowkaId = 5,
                            Specjalizacja = "Onkolog"
                        });
                });

            modelBuilder.Entity("API.Alimed.Entities.Pacjent", b =>
                {
                    b.Property<int>("PacjentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PacjentId"));

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Imie")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("longtext");

                    b.Property<string>("Pesel")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("PacjentId");

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Pacjenci");

                    b.HasData(
                        new
                        {
                            PacjentId = 1,
                            DataUrodzenia = new DateTime(1990, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Alicja",
                            Nazwisko = "Bąk",
                            Pesel = "90050112345",
                            UserId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PacjentId = 2,
                            DataUrodzenia = new DateTime(1985, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Robert",
                            Nazwisko = "Cygan",
                            Pesel = "85112054321",
                            UserId = new Guid("b0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            PacjentId = 3,
                            DataUrodzenia = new DateTime(1975, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Karolina",
                            Nazwisko = "Duda",
                            Pesel = "75021598765",
                            UserId = new Guid("b0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            PacjentId = 4,
                            DataUrodzenia = new DateTime(2001, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Maksymilian",
                            Nazwisko = "Falkowski",
                            Pesel = "01081033344",
                            UserId = new Guid("b0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            PacjentId = 5,
                            DataUrodzenia = new DateTime(1968, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Zofia",
                            Nazwisko = "Górecka",
                            Pesel = "68092288899",
                            UserId = new Guid("b0000000-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("API.Alimed.Entities.Placowka", b =>
                {
                    b.Property<int>("PlacowkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlacowkaId"));

                    b.Property<string>("Nazwa")
                        .HasColumnType("longtext");

                    b.Property<string>("NumerKonta")
                        .HasColumnType("longtext");

                    b.HasKey("PlacowkaId");

                    b.ToTable("Placowki");

                    b.HasData(
                        new
                        {
                            PlacowkaId = 1,
                            Nazwa = "Przychodnia Zdrowie",
                            NumerKonta = "12 3456 7890 1234 5678 0000"
                        },
                        new
                        {
                            PlacowkaId = 2,
                            Nazwa = "Szpital Miejski",
                            NumerKonta = "98 7654 3210 9876 5432 0000"
                        },
                        new
                        {
                            PlacowkaId = 3,
                            Nazwa = "Centrum Rehabilitacji",
                            NumerKonta = "37 1020 5555 1234 5678 9012 0000"
                        },
                        new
                        {
                            PlacowkaId = 4,
                            Nazwa = "Novum Centrum Diagnostyki",
                            NumerKonta = "61 1140 2000 0000 1111 2222 3333"
                        },
                        new
                        {
                            PlacowkaId = 5,
                            Nazwa = "VitaMed Klinika",
                            NumerKonta = "85 2490 0000 0000 4567 8901 2345"
                        });
                });

            modelBuilder.Entity("API.Alimed.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("API.Alimed.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("GithubId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GithubName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsGithubUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("GithubId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            IsGithubUser = false,
                            Role = 2,
                            Username = "admin_alimed"
                        },
                        new
                        {
                            UserId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            IsGithubUser = false,
                            Role = 0,
                            Username = "pacjent1"
                        },
                        new
                        {
                            UserId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            IsGithubUser = false,
                            Role = 0,
                            Username = "pacjent2"
                        },
                        new
                        {
                            UserId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            IsGithubUser = false,
                            Role = 0,
                            Username = "pacjent3"
                        },
                        new
                        {
                            UserId = new Guid("b0000000-0000-0000-0000-000000000004"),
                            IsGithubUser = false,
                            Role = 0,
                            Username = "pacjent4"
                        },
                        new
                        {
                            UserId = new Guid("b0000000-0000-0000-0000-000000000005"),
                            IsGithubUser = false,
                            Role = 0,
                            Username = "pacjent5"
                        });
                });

            modelBuilder.Entity("API.Alimed.Entities.Wizyta", b =>
                {
                    b.Property<int>("WizytaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WizytaId"));

                    b.Property<DateTime>("DataWizyty")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Diagnoza")
                        .HasColumnType("longtext");

                    b.Property<int?>("LekarzId")
                        .HasColumnType("int");

                    b.Property<int?>("PacjentId")
                        .HasColumnType("int");

                    b.Property<int?>("PlacowkaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("WizytaId");

                    b.HasIndex("PacjentId");

                    b.HasIndex("PlacowkaId");

                    b.HasIndex("LekarzId", "PlacowkaId", "DataWizyty")
                        .IsUnique();

                    b.ToTable("Wizyty");

                    b.HasData(
                        new
                        {
                            WizytaId = 1,
                            DataWizyty = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Grypa sezonowa",
                            LekarzId = 1,
                            PacjentId = 1,
                            PlacowkaId = 1,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 2,
                            DataWizyty = new DateTime(2025, 2, 20, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Kontrola ciśnienia",
                            LekarzId = 7,
                            PacjentId = 1,
                            PlacowkaId = 3,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 3,
                            DataWizyty = new DateTime(2025, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Badanie okresowe",
                            LekarzId = 15,
                            PacjentId = 1,
                            PlacowkaId = 4,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 4,
                            DataWizyty = new DateTime(2025, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Wizyta u kardiologa",
                            LekarzId = 37,
                            PacjentId = 1,
                            PlacowkaId = 5,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 5,
                            DataWizyty = new DateTime(2025, 5, 10, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Badanie krwi (planowana)",
                            LekarzId = 4,
                            PacjentId = 1,
                            PlacowkaId = 2,
                            Status = 0
                        },
                        new
                        {
                            WizytaId = 6,
                            DataWizyty = new DateTime(2025, 1, 25, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Ból pleców",
                            LekarzId = 5,
                            PacjentId = 2,
                            PlacowkaId = 2,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 7,
                            DataWizyty = new DateTime(2025, 2, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Skręcenie kostki",
                            LekarzId = 21,
                            PacjentId = 2,
                            PlacowkaId = 4,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 8,
                            DataWizyty = new DateTime(2025, 3, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Kontrola po urazie",
                            LekarzId = 39,
                            PacjentId = 2,
                            PlacowkaId = 5,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 9,
                            DataWizyty = new DateTime(2025, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Wizyta u dermatologa",
                            LekarzId = 20,
                            PacjentId = 2,
                            PlacowkaId = 4,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 10,
                            DataWizyty = new DateTime(2025, 5, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Wizyta kontrolna (planowana)",
                            LekarzId = 1,
                            PacjentId = 2,
                            PlacowkaId = 1,
                            Status = 0
                        },
                        new
                        {
                            WizytaId = 11,
                            DataWizyty = new DateTime(2025, 1, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Wizyta u endokrynologa",
                            LekarzId = 8,
                            PacjentId = 3,
                            PlacowkaId = 3,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 12,
                            DataWizyty = new DateTime(2025, 2, 28, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Problemy ze snem",
                            LekarzId = 30,
                            PacjentId = 3,
                            PlacowkaId = 4,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 13,
                            DataWizyty = new DateTime(2025, 3, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Badania hormonalne",
                            LekarzId = 42,
                            PacjentId = 3,
                            PlacowkaId = 5,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 14,
                            DataWizyty = new DateTime(2025, 4, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Konsultacja psychiatryczna",
                            LekarzId = 48,
                            PacjentId = 3,
                            PlacowkaId = 5,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 15,
                            DataWizyty = new DateTime(2025, 5, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Konsultacja ginekologiczna (planowana)",
                            LekarzId = 6,
                            PacjentId = 3,
                            PlacowkaId = 2,
                            Status = 0
                        },
                        new
                        {
                            WizytaId = 16,
                            DataWizyty = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Ból głowy",
                            LekarzId = 23,
                            PacjentId = 4,
                            PlacowkaId = 4,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 17,
                            DataWizyty = new DateTime(2025, 2, 14, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Kontrola okulistyczna",
                            LekarzId = 10,
                            PacjentId = 4,
                            PlacowkaId = 3,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 18,
                            DataWizyty = new DateTime(2025, 3, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Wizyta u pulmonologa",
                            LekarzId = 27,
                            PacjentId = 4,
                            PlacowkaId = 4,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 19,
                            DataWizyty = new DateTime(2025, 4, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Zapalenie spojówek",
                            LekarzId = 44,
                            PacjentId = 4,
                            PlacowkaId = 5,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 20,
                            DataWizyty = new DateTime(2025, 5, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Szczepienie (planowane)",
                            LekarzId = 2,
                            PacjentId = 4,
                            PlacowkaId = 1,
                            Status = 0
                        },
                        new
                        {
                            WizytaId = 21,
                            DataWizyty = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Ból stawów",
                            LekarzId = 12,
                            PacjentId = 5,
                            PlacowkaId = 3,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 22,
                            DataWizyty = new DateTime(2025, 2, 5, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Zalecenia reumatologiczne",
                            LekarzId = 28,
                            PacjentId = 5,
                            PlacowkaId = 4,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 23,
                            DataWizyty = new DateTime(2025, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Kontrola geriatryczna",
                            LekarzId = 31,
                            PacjentId = 5,
                            PlacowkaId = 4,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 24,
                            DataWizyty = new DateTime(2025, 4, 14, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Konsultacja onkologiczna",
                            LekarzId = 50,
                            PacjentId = 5,
                            PlacowkaId = 5,
                            Status = 1
                        },
                        new
                        {
                            WizytaId = 25,
                            DataWizyty = new DateTime(2025, 5, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnoza = "Kontrola (planowana)",
                            LekarzId = 3,
                            PacjentId = 5,
                            PlacowkaId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("API.Alimed.Entities.GodzinyPracyLekarza", b =>
                {
                    b.HasOne("API.Alimed.Entities.Lekarz", "Lekarz")
                        .WithMany()
                        .HasForeignKey("LekarzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Alimed.Entities.Placowka", "Placowka")
                        .WithMany()
                        .HasForeignKey("PlacowkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lekarz");

                    b.Navigation("Placowka");
                });

            modelBuilder.Entity("API.Alimed.Entities.Lekarz", b =>
                {
                    b.HasOne("API.Alimed.Entities.Placowka", "Placowka")
                        .WithMany("Lekarze")
                        .HasForeignKey("PlacowkaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Alimed.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("API.Alimed.Entities.Lekarz", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Placowka");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Alimed.Entities.Pacjent", b =>
                {
                    b.HasOne("API.Alimed.Entities.User", "User")
                        .WithOne("Pacjent")
                        .HasForeignKey("API.Alimed.Entities.Pacjent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("API.Alimed.Entities.Adres", "AdresZamieszkania", b1 =>
                        {
                            b1.Property<int>("PacjentId")
                                .HasColumnType("int");

                            b1.Property<string>("KodPocztowy")
                                .HasColumnType("longtext");

                            b1.Property<string>("Kraj")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("longtext")
                                .HasDefaultValue("Polska");

                            b1.Property<string>("Miasto")
                                .HasColumnType("longtext");

                            b1.Property<string>("NumerDomu")
                                .HasColumnType("longtext");

                            b1.Property<string>("Ulica")
                                .HasColumnType("longtext");

                            b1.HasKey("PacjentId");

                            b1.ToTable("Pacjenci");

                            b1.WithOwner()
                                .HasForeignKey("PacjentId");

                            b1.HasData(
                                new
                                {
                                    PacjentId = 1,
                                    KodPocztowy = "00-010",
                                    Kraj = "Polska",
                                    Miasto = "Warszawa",
                                    NumerDomu = "3/1",
                                    Ulica = "Długa"
                                },
                                new
                                {
                                    PacjentId = 2,
                                    KodPocztowy = "30-011",
                                    Kraj = "Polska",
                                    Miasto = "Kraków",
                                    NumerDomu = "15",
                                    Ulica = "Krótka"
                                },
                                new
                                {
                                    PacjentId = 3,
                                    KodPocztowy = "80-123",
                                    Kraj = "Polska",
                                    Miasto = "Gdańsk",
                                    NumerDomu = "2A",
                                    Ulica = "Wodna"
                                },
                                new
                                {
                                    PacjentId = 4,
                                    KodPocztowy = "60-700",
                                    Kraj = "Polska",
                                    Miasto = "Poznań",
                                    NumerDomu = "88B",
                                    Ulica = "Rzeczna"
                                },
                                new
                                {
                                    PacjentId = 5,
                                    KodPocztowy = "50-400",
                                    Kraj = "Polska",
                                    Miasto = "Wrocław",
                                    NumerDomu = "45",
                                    Ulica = "Północna"
                                });
                        });

                    b.Navigation("AdresZamieszkania");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Alimed.Entities.Placowka", b =>
                {
                    b.OwnsOne("API.Alimed.Entities.Adres", "AdresPlacowki", b1 =>
                        {
                            b1.Property<int>("PlacowkaId")
                                .HasColumnType("int");

                            b1.Property<string>("KodPocztowy")
                                .HasColumnType("longtext");

                            b1.Property<string>("Kraj")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("longtext")
                                .HasDefaultValue("Polska");

                            b1.Property<string>("Miasto")
                                .HasColumnType("longtext");

                            b1.Property<string>("NumerDomu")
                                .HasColumnType("longtext");

                            b1.Property<string>("Ulica")
                                .HasColumnType("longtext");

                            b1.HasKey("PlacowkaId");

                            b1.ToTable("Placowki");

                            b1.WithOwner()
                                .HasForeignKey("PlacowkaId");

                            b1.HasData(
                                new
                                {
                                    PlacowkaId = 1,
                                    KodPocztowy = "00-001",
                                    Kraj = "Polska",
                                    Miasto = "Warszawa",
                                    NumerDomu = "10",
                                    Ulica = "Lipowa"
                                },
                                new
                                {
                                    PlacowkaId = 2,
                                    KodPocztowy = "01-234",
                                    Kraj = "Polska",
                                    Miasto = "Kraków",
                                    NumerDomu = "5A",
                                    Ulica = "Kwiatowa"
                                },
                                new
                                {
                                    PlacowkaId = 3,
                                    KodPocztowy = "80-800",
                                    Kraj = "Polska",
                                    Miasto = "Gdańsk",
                                    NumerDomu = "21B/3",
                                    Ulica = "Słoneczna"
                                },
                                new
                                {
                                    PlacowkaId = 4,
                                    KodPocztowy = "60-900",
                                    Kraj = "Polska",
                                    Miasto = "Poznań",
                                    NumerDomu = "77",
                                    Ulica = "Przemysłowa"
                                },
                                new
                                {
                                    PlacowkaId = 5,
                                    KodPocztowy = "50-101",
                                    Kraj = "Polska",
                                    Miasto = "Wrocław",
                                    NumerDomu = "4",
                                    Ulica = "Leśna Aleja"
                                });
                        });

                    b.Navigation("AdresPlacowki");
                });

            modelBuilder.Entity("API.Alimed.Entities.RefreshToken", b =>
                {
                    b.HasOne("API.Alimed.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Alimed.Entities.Wizyta", b =>
                {
                    b.HasOne("API.Alimed.Entities.Lekarz", "Lekarz")
                        .WithMany("Wizyty")
                        .HasForeignKey("LekarzId");

                    b.HasOne("API.Alimed.Entities.Pacjent", "Pacjent")
                        .WithMany("Wizyty")
                        .HasForeignKey("PacjentId");

                    b.HasOne("API.Alimed.Entities.Placowka", "Placowka")
                        .WithMany("Wizyty")
                        .HasForeignKey("PlacowkaId");

                    b.Navigation("Lekarz");

                    b.Navigation("Pacjent");

                    b.Navigation("Placowka");
                });

            modelBuilder.Entity("API.Alimed.Entities.Lekarz", b =>
                {
                    b.Navigation("Wizyty");
                });

            modelBuilder.Entity("API.Alimed.Entities.Pacjent", b =>
                {
                    b.Navigation("Wizyty");
                });

            modelBuilder.Entity("API.Alimed.Entities.Placowka", b =>
                {
                    b.Navigation("Lekarze");

                    b.Navigation("Wizyty");
                });

            modelBuilder.Entity("API.Alimed.Entities.User", b =>
                {
                    b.Navigation("Pacjent");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
